version: '3'
services:
  nginx:
    ports:
      - "4000:80"
  nodeapp:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=yash
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yash
      - MONGO_INITDB_ROOT_PASSWORD=password
