version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  nodeapp:
    build: .
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - mongo
        
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yash
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    ports:
      - "27018:27017"
      
  redis:
    image: redis
    ports:
      - "6300:6379"
      
volumes:
  mongo-db: